# Generated by Django 4.2.2 on 2023-06-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('familiya', models.CharField(max_length=40)),
                ('manzil', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.kurs')),
            ],
        ),
    ]
