# Generated by Django 4.2.2 on 2023-06-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yoshi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
