# Generated by Django 4.2.2 on 2023-06-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_student_yoshi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('familiya', models.CharField(max_length=30)),
                ('yosh', models.IntegerField()),
                ('lavozim', models.CharField(max_length=50)),
                ('ish_staji', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
